// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKGepFyObzMFFftpAto9IVF9ffLSsXqFs',
    appId: '1:757304996649:web:8f3870e5433e54326b7d38',
    messagingSenderId: '757304996649',
    projectId: 'sinflixxx',
    authDomain: 'sinflixxx.firebaseapp.com',
    storageBucket: 'sinflixxx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_0itdaHtHRcvTtNqB6EiT0hsNPK87A4',
    appId: '1:757304996649:android:b3a8d062568361ef6b7d38',
    messagingSenderId: '757304996649',
    projectId: 'sinflixxx',
    storageBucket: 'sinflixxx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD06XnZijwxOlXa-X5JAGy-IhGD1qvMvjo',
    appId: '1:757304996649:ios:2fe3f70706964ffd6b7d38',
    messagingSenderId: '757304996649',
    projectId: 'sinflixxx',
    storageBucket: 'sinflixxx.firebasestorage.app',
    iosBundleId: 'com.example.sinflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD06XnZijwxOlXa-X5JAGy-IhGD1qvMvjo',
    appId: '1:757304996649:ios:2fe3f70706964ffd6b7d38',
    messagingSenderId: '757304996649',
    projectId: 'sinflixxx',
    storageBucket: 'sinflixxx.firebasestorage.app',
    iosBundleId: 'com.example.sinflix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKGepFyObzMFFftpAto9IVF9ffLSsXqFs',
    appId: '1:757304996649:web:b8ca3c94dba05a126b7d38',
    messagingSenderId: '757304996649',
    projectId: 'sinflixxx',
    authDomain: 'sinflixxx.firebaseapp.com',
    storageBucket: 'sinflixxx.firebasestorage.app',
  );
}
